name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true

      - name: Run Tests
        run: go test ./...

      - name: Run Go Vet
        run: go vet ./...

      - name: Install Staticcheck and Run
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
